# Generated by Django 3.2.25 on 2025-06-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=260)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
